/*
 * OrgstudiesUI.java
 *
 * Created on February 8, 2005, 6:18 PM
 */

package nv2d.plugins.standard;

import nv2d.ui.NController;

/**
 *
 * @author  bshi
 */
public class OrgstudiesUI extends java.awt.Dialog {
    private static final String [] _optOperator = {"=", "<", ">", "<=", ">="};
    
    private NController _ctl;
    private Orgstudies _org;
    
    /** Creates new form OrgstudiesUI */
    public OrgstudiesUI(java.awt.Frame parent, NController ctl, Orgstudies org) {
        super(parent, true);
        int j;
        _ctl = ctl;
        _org = org;
        
        initComponents();
        
        Object [] years = org.getYearListing();
        for(j = 0; j < years.length; j++) {
            _year.addItem(years[j]);
        }
        
        for(j = 0; j < _optOperator.length; j++) {
            _binaryOperator.addItem(_optOperator[j]);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        _northPanel = new javax.swing.JPanel();
        _binaryOperator = new javax.swing.JComboBox();
        _year = new javax.swing.JComboBox();
        _filterExectute = new javax.swing.JButton();
        _wholeSet = new javax.swing.JCheckBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        _northPanel.setLayout(new java.awt.GridLayout(1, 0));

        _northPanel.setOpaque(false);
        _northPanel.add(_binaryOperator);

        _northPanel.add(_year);

        _filterExectute.setText("Filter");
        _filterExectute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _filterExectuteActionPerformed(evt);
            }
        });

        _northPanel.add(_filterExectute);

        add(_northPanel, java.awt.BorderLayout.CENTER);

        _wholeSet.setText("Filter on whole dataset");
        add(_wholeSet, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void _filterExectuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__filterExectuteActionPerformed
        // TODO add your handling code here:
        
        /*
        				Object [] fargs = new Object[2];
				Vertex selectedVertex = (Vertex) vertices.getSelectedItem();
				String selectedDegree = (String) degree.getSelectedItem();
				Integer degree = null;

				try {
					degree = Integer.valueOf(selectedDegree.substring(0, 1));
				} catch (NumberFormatException exception) {
					// show all nodes
					degree = new Integer(-1);
				}

				fargs[0] = selectedVertex;
				fargs[1] = degree;

				ctl.runFilter(fargs);
         */
        Object [] fargs = new Object[2];
        fargs[0] = _binaryOperator.getSelectedItem();
        fargs[1] = _year.getSelectedItem();
        _ctl.setFilter(_org);
        _ctl.runFilter(fargs, _wholeSet.isSelected());
        
        
    }//GEN-LAST:event__filterExectuteActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     *
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrgstudiesUI(new java.awt.Frame(), true).setVisible(true);
            }
        });
    }
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox _binaryOperator;
    private javax.swing.JButton _filterExectute;
    private javax.swing.JPanel _northPanel;
    private javax.swing.JCheckBox _wholeSet;
    private javax.swing.JComboBox _year;
    // End of variables declaration//GEN-END:variables
    
}
