/*
 * BottomPanel.java
 *
 * Created on February 7, 2005, 4:43 PM
 */

package nv2d.ui;



/**
 *
 * @author  bshi
 */
public class BottomPanel extends javax.swing.JPanel {
    NController _ctl;
    
    /** Creates new form BottomPanel */
    public BottomPanel(NController ctl) {
        _ctl = ctl;
        
        initComponents();
        setPreferredSize(new java.awt.Dimension(700, 25));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        _start = new javax.swing.JButton();
        _stop = new javax.swing.JButton();
        _center = new javax.swing.JButton();
        _reset = new javax.swing.JButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(2, 0));
        _start.setText(" Start ");
        _start.setToolTipText("Start the interative layout.");
        _start.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        _start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _startActionPerformed(evt);
            }
        });

        add(_start);

        _stop.setText(" Stop ");
        _stop.setToolTipText("Stop the interactive layout.");
        _stop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        _stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _stopActionPerformed(evt);
            }
        });

        add(_stop);

        _center.setText(" Center ");
        _center.setToolTipText("Center the graph according to the center of mass of the vertices.");
        _center.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        _center.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _centerActionPerformed(evt);
            }
        });

        add(_center);

        _reset.setText(" Reset ");
        _reset.setToolTipText("Reset the graph to a random layout.");
        _reset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        _reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _resetActionPerformed(evt);
            }
        });

        add(_reset);

    }//GEN-END:initComponents

    private void _startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__startActionPerformed
        // TODO add your handling code here:
        _ctl.getView().startForceDirectedLayout();
    }//GEN-LAST:event__startActionPerformed

    private void _stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__stopActionPerformed
        // TODO add your handling code here:
        _ctl.getView().stopForceDirectedLayout();
    }//GEN-LAST:event__stopActionPerformed

    private void _centerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__centerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event__centerActionPerformed

    private void _resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__resetActionPerformed
        // TODO add your handling code here:
        _ctl.getView().stopForceDirectedLayout();
        _ctl.getView().doRandomLayout();
    }//GEN-LAST:event__resetActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _center;
    private javax.swing.JButton _reset;
    private javax.swing.JButton _start;
    private javax.swing.JButton _stop;
    // End of variables declaration//GEN-END:variables
    
}
