/*
 * HistoryUI.java
 *
 * Created on March 2, 2005, 3:10 PM
 */

package nv2d.ui;

/**
 *
 * @author  bshi
 */
public class HistoryUI extends javax.swing.JPanel {
	private javax.swing.DefaultListModel _historyElements;
	
	/** Creates new form HistoryUI */
	public HistoryUI(javax.swing.DefaultListModel historyElements) {
		_historyElements = historyElements;
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents
        _scrollPane = new javax.swing.JScrollPane();
        _jlist = new javax.swing.JList(_historyElements);
        _jlist.setCellRenderer(new HistoryListRenderer());

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder(null, "History", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        _scrollPane.setViewportView(_jlist);

        add(_scrollPane, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList _jlist;
    private javax.swing.JScrollPane _scrollPane;
    // End of variables declaration//GEN-END:variables
	
}
