/*
 * PluginManagerUI.java
 *
 * Created on February 5, 2005, 2:07 PM
 */

package nv2d.ui;

/**
 *
 * @author  bshi
 */
public class PluginManagerUI extends javax.swing.JDialog {
    
    /** Creates new form PluginManagerUI */
    public PluginManagerUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        _manager = new javax.swing.JPanel();
        _managerListSP = new javax.swing.JScrollPane();
        _managerListPanel = new javax.swing.JPanel();
        _managerDescSP = new javax.swing.JScrollPane();
        _managerDescTxt = new javax.swing.JTextPane();
        _load = new javax.swing.JPanel();
        _loadLabel = new javax.swing.JLabel();
        _loadURI = new javax.swing.JTextField();
        _loadExec = new javax.swing.JButton();
        _sec = new javax.swing.JPanel();
        _secList = new javax.swing.JList();
        _secAdd = new javax.swing.JButton();
        _secRem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        _manager.setLayout(new javax.swing.BoxLayout(_manager, javax.swing.BoxLayout.Y_AXIS));

        _manager.setBorder(new javax.swing.border.TitledBorder("Plugin Manager"));
        _managerListSP.setViewportView(_managerListPanel);

        _manager.add(_managerListSP);

        _managerDescSP.setViewportView(_managerDescTxt);

        _manager.add(_managerDescSP);

        getContentPane().add(_manager, java.awt.BorderLayout.CENTER);

        _load.setLayout(new javax.swing.BoxLayout(_load, javax.swing.BoxLayout.X_AXIS));

        _load.setBorder(new javax.swing.border.TitledBorder("Load Plugins"));
        _loadLabel.setText("URI  ");
        _load.add(_loadLabel);

        _loadURI.setText("jTextField1");
        _load.add(_loadURI);

        _loadExec.setText("Load");
        _load.add(_loadExec);

        getContentPane().add(_load, java.awt.BorderLayout.NORTH);

        _sec.setLayout(new java.awt.BorderLayout());

        _sec.setBorder(new javax.swing.border.TitledBorder("Security"));
        _sec.add(_secList, java.awt.BorderLayout.CENTER);

        _secAdd.setText("Add Location");
        _sec.add(_secAdd, java.awt.BorderLayout.NORTH);

        _secRem.setText("Remove Location");
        _sec.add(_secRem, java.awt.BorderLayout.SOUTH);

        getContentPane().add(_sec, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PluginManagerUI(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _load;
    private javax.swing.JButton _loadExec;
    private javax.swing.JLabel _loadLabel;
    private javax.swing.JTextField _loadURI;
    private javax.swing.JPanel _manager;
    private javax.swing.JScrollPane _managerDescSP;
    private javax.swing.JTextPane _managerDescTxt;
    private javax.swing.JPanel _managerListPanel;
    private javax.swing.JScrollPane _managerListSP;
    private javax.swing.JPanel _sec;
    private javax.swing.JButton _secAdd;
    private javax.swing.JList _secList;
    private javax.swing.JButton _secRem;
    // End of variables declaration//GEN-END:variables
    
}
