/**
 * NV2D - Social Network Visualization
 * Copyright (C) 2005 Bo Shi
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * Created on March 16, 2005, 2:14 PM
 */

package nv2d.ui;

/**
 *
 * @author  bshi
 */
public class ColorLegendUI extends javax.swing.JPanel {
	private ColorLegend _legend;
	
	/** Creates new form ColorLegendUI */
	public ColorLegendUI(ColorLegend legend) {
		_legend = legend;
		
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents
        _scrollPane = new javax.swing.JScrollPane();
        _jlist = new javax.swing.JList(_legend.getListModel());
        _jlist.setCellRenderer(new ColorLegendRenderer());
        _attributeName = new javax.swing.JLabel(_legend.getAttribute());

        setLayout(new java.awt.BorderLayout());

        _scrollPane.setViewportView(_jlist);

        add(_scrollPane, java.awt.BorderLayout.CENTER);

        add(_attributeName, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _attributeName;
    private javax.swing.JList _jlist;
    private javax.swing.JScrollPane _scrollPane;
    // End of variables declaration//GEN-END:variables
	
}
