/**
 * NV2D - Social Network Visualization
 * Copyright (C) 2005 Bo Shi
 * $Id$
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * Created on March 16, 2005, 2:14 PM
 */

package nv2d.ui;

import java.awt.*;
import javax.swing.*;

import nv2d.utils.Pair;

/**
 *
 * @author  bshi
 */
public class ColorLegendUI extends javax.swing.JPanel {
	private NController _ctl;
	private ColorLegend _legend;
	
	/** Creates new form ColorLegendUI */
	public ColorLegendUI(NController ctl, ColorLegend legend) {
		_ctl = ctl;
		_legend = legend;
		
		initComponents();
	}
	
	public String legendProperty() {
		return _legend.getAttribute();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents
        _scrollPane = new javax.swing.JScrollPane();
        _jlist = new javax.swing.JList(_legend.getFilteredListModel(_ctl.getSubgraph()));
        _jlist.setCellRenderer(new ColorLegendListRenderer());
        _topPanel = new javax.swing.JPanel();
        _legendAttribute = new JLabel("Color Legend - " + _legend.getAttribute());

        setLayout(new java.awt.BorderLayout());

        _scrollPane.setViewportView(_jlist);

        add(_scrollPane, java.awt.BorderLayout.CENTER);

        _topPanel.setLayout(new java.awt.BorderLayout());

        _topPanel.add(_legendAttribute, java.awt.BorderLayout.WEST);

        add(_topPanel, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList _jlist;
    private javax.swing.JLabel _legendAttribute;
    private javax.swing.JScrollPane _scrollPane;
    private javax.swing.JPanel _topPanel;
    // End of variables declaration//GEN-END:variables
	
}

class ColorLegendListRenderer extends DefaultListCellRenderer {
	public Component getListCellRendererComponent(JList list,
			Object value,
			int index,
			boolean isSelected,
			boolean hasFocus) {
		final JLabel label =
				(JLabel)super.getListCellRendererComponent(list,
				value,
				index,
				isSelected,
				hasFocus);
		
		// pair.car() -> key
		// pair.cdr() -> color
		final Pair pair = (Pair) value;
		String iconLabel;
		label.setIcon(new ColorIcon((Color) pair.cdr()));
		iconLabel = pair.car().toString();
		label.setText((iconLabel.length() > 20 ? iconLabel.substring(0, 20) + "..." : iconLabel));
		label.setToolTipText(iconLabel);
		
		label.setVerticalTextPosition(SwingConstants.TOP);
		label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
		return(label);
	}
}